### ISSUE TITLE
[idea] Show inherited methods/properties

### ISSUE THREAD

**Issue by nkkollaw** [7ute/symbols-list#40]
Plugin works great.

I would be really awesome though if it showed a class' inherited methods/properties.

**Comment by mbuc82** [comment]
Hello @nkkollaw ,

in my opinion, this would be difficult with the current implementation (also in terms of performance), because the package analyses the currently opened code on a regex base in time (on file load, save actions etc.). It doesn't scan a (project-)folder recursively, what makes it difficult to follow possible inheritance paths.

I'm not sure, if you have a detailed picture in mind about such a functionality, that you could share, but in case of doubt we could keep your proposal for further versions (hopefully we can realize it sometimes).

Best regards

**Comment by nkkollaw** [comment]
Got it.

The package php-integrator would provide an API that one can query (for PHP, though). I have no idea about other languages.

I wish I could help, but I'm not familiar with Electron. :-/

**Comment by 7ute** [comment]
Even if I understand the need of exposing inherited methods and properties, I thinks goes away from the original purpose of this plugin : having a lightweight navigation helper, that shows the structure of your current file at glance.

That analysis feature would have its place in a contextual menu on a class or instance click ( kinda like Xcode), or even another analysis panel, more project related.

Here's an idea for another plugin ;)
And if we (or you!) make that plugin someday, we've got a whole list of feature we'ld love to see, to expose some common frameworks structures (Symfony and Laravel for PHP; Ionic, Angular and Atom for JS/TS/CS). In that case, php-integrator will for sure be of good help.

I'm gonna close the thread, but feel free to drop ideas going that way in it!
